### ISSUE TITLE
Windows implementation

### ISSUE THREAD

**Issue by PumpkinSeed** [PumpkinSeed/bluetooth-rw#1]
Implement windows Read/Write mechanism. 

Resources:

- https://github.com/golang/go/issues/52958
- https://docs.microsoft.com/en-us/windows/win32/api/ws2bth/ns-ws2bth-sockaddr_bth

**Comment by MatejMagat305** [comment]
Can I ask: it is posible to connect as client to server?

**Comment by PumpkinSeed** [comment]
> Can I ask: it is posible to connect as client to server?

What do you mean? Can you share details?

**Comment by MatejMagat305** [comment]
i am sorry, but in example is only discover (probably server side) ..., thank for answer

**Comment by PumpkinSeed** [comment]
You can find the implementation [here](https://github.com/infiniteloopcloud/bluetooth-go)

**Comment by MatejMagat305** [comment]
och, sorry, thank
